const OK_STATUS_CODE = 200;
const CREATE_STATUS_CODE = 201;
const BAD_REQUEST_STATUS_CODE = 400;
const NOT_FOUND_STATUS_CODE = 404;
const INTERNAL_SERVER_ERROR_STATUS_CODE = 500;
const UNAUTHORIZATION_STATUS_CODE = 401;
const CONFLICT_STATUS_CODE = 409;
const FORBIDDEN_STATUS_CODE = 403;

const JWT_SECRET = '686b888065dc0105ef5799cae9ea58bae758dec68a657e4f3ff2d673a2048cdd';

module.exports = {
  OK_STATUS_CODE,
  CREATE_STATUS_CODE,
  BAD_REQUEST_STATUS_CODE,
  NOT_FOUND_STATUS_CODE,
  INTERNAL_SERVER_ERROR_STATUS_CODE,
  UNAUTHORIZATION_STATUS_CODE,
  CONFLICT_STATUS_CODE,
  FORBIDDEN_STATUS_CODE,
  JWT_SECRET,
};
