const OK_STATUS_CODE = 200;
const CREATE_STATUS_CODE = 201;
const BAD_REQUEST_STATUS_CODE = 400;
const NOT_FOUND_STATUS_CODE = 404;
const INTERNAL_SERVER_ERROR_STATUS_CODE = 500;
const UNAUTHORIZATION_STATUS_CODE = 401;
const CONFLICT_STATUS_CODE = 409;
const FORBIDDEN_STATUS_CODE = 403;

module.exports = {
  OK_STATUS_CODE,
  CREATE_STATUS_CODE,
  BAD_REQUEST_STATUS_CODE,
  NOT_FOUND_STATUS_CODE,
  INTERNAL_SERVER_ERROR_STATUS_CODE,
  UNAUTHORIZATION_STATUS_CODE,
  CONFLICT_STATUS_CODE,
  FORBIDDEN_STATUS_CODE,
};
